version: "3.6"

services:
  psql:
    image: "postgres:10-alpine"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chitchat
    volumes:
      - ../sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ../db:/var/lib/postgresql/data

  chitchat:
    image: "duongtomho/chitchat:latest"
    ports:
      - "8080:8080"
    depends_on:
      - psql
    volumes:
      - ../config/config.yaml:/app/config/config.yaml
